# This file was generated by GoReleaser. DO NOT EDIT.
cask "septiembre" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "39b44a5a72f0f9c4e5f1a0ccd5750db278dfc30fcfac2baf0f322fcfb0b8ab4b"
      url "https://github.com/septiembre-ai/septiembre-cli/releases/download/v#{version}/septiembre_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9427174ba105ab7665fabf7ad4815fc0b2f96801a84c37119a6962aa122b89eb"
      url "https://github.com/septiembre-ai/septiembre-cli/releases/download/v#{version}/septiembre_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "80401b573efc7d4c69abce5b28280a4a238cf3e023800fbd5c7f9fdf19f01783"
      url "https://github.com/septiembre-ai/septiembre-cli/releases/download/v#{version}/septiembre_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1e3ff8808d34516888a42d1467b9268ede95ac194b5534216ea4c4cd2a866c9"
      url "https://github.com/septiembre-ai/septiembre-cli/releases/download/v#{version}/septiembre_#{version}_linux_arm64.tar.gz"
    end
  end

  name "septiembre"
  desc "CLI for the Septiembre cloud platform"
  homepage "https://cloud.septiembre.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "septiembre"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/septiembre"]
    end
  end

  # No zap stanza required

end
