# This file was generated by GoReleaser. DO NOT EDIT.
cask "septiembre" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "38fa76497f586aa3ee060092c60a054c92dacffae28aefb368276ac8a4549cb2"
      url "https://github.com/septiembre-ai/septiembre-cli/releases/download/v#{version}/septiembre_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "94fd1c47f159f7caf239b3ad4673f4769626cc48fe6fd44088301813d614f15d"
      url "https://github.com/septiembre-ai/septiembre-cli/releases/download/v#{version}/septiembre_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e92dc8a655fcf29045901ae492f5711ca3cba13ab0ee95c3fe1c12b3f497db1a"
      url "https://github.com/septiembre-ai/septiembre-cli/releases/download/v#{version}/septiembre_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "13c08ca0078db37d1a6f387ca5cb21dc71256ae6e1ff29caa2c850a5f2cd82a4"
      url "https://github.com/septiembre-ai/septiembre-cli/releases/download/v#{version}/septiembre_#{version}_linux_arm64.tar.gz"
    end
  end

  name "septiembre"
  desc "CLI for the Septiembre cloud platform"
  homepage "https://cloud.septiembre.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "septiembre"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/septiembre"]
    end
  end

  # No zap stanza required

end
