# This file was generated by GoReleaser. DO NOT EDIT.
cask "septiembre" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "90f203a95c4a5ea6e624167f1bfe259e1ae553fefe53747579ff7e819f0f801b"
      url "https://github.com/septiembre-ai/septiembre-cli/releases/download/v#{version}/septiembre_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "df48b5d68c27eb54137802d9f33f421fc8b2dbf9fe1cf77a4251ece0c50d18be"
      url "https://github.com/septiembre-ai/septiembre-cli/releases/download/v#{version}/septiembre_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4205bacbe382b311f2e8b3d5fee4759c5280e4ae13eac9f5bb24d23d3974a871"
      url "https://github.com/septiembre-ai/septiembre-cli/releases/download/v#{version}/septiembre_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0ab5a5d1d6c0828a2a91b37c14e38ed3c998fe930da8c6ab7115864e2a6413dd"
      url "https://github.com/septiembre-ai/septiembre-cli/releases/download/v#{version}/septiembre_#{version}_linux_arm64.tar.gz"
    end
  end

  name "septiembre"
  desc "CLI for the Septiembre cloud platform"
  homepage "https://cloud.septiembre.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "septiembre"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/septiembre"]
    end
  end

  # No zap stanza required

end
